name: goreleaser test

on:
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/goreleaser_test.yml"
      - ".github/workflows/goreleaser.yml"

permissions:
  contents: write

jobs:
  goreleaser_test:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.3
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v2.4.4
          args: release --clean --skip publish --snapshot
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
